---
- name: Cleanup of old config files
  file: path=/etc/nginx/conf.d/
    state: absent

- name: Create config folder
  file: path=/etc/nginx/conf.d/ state=directory

- name: deploy reverse proxy configurations
  template:
    src: reverse-proxy.conf.j2
    dest: "{{ nginx_reverse_proxy_config_directory }}/{{ item.config_name }}.conf"
  with_items: "{{ nginx_reverse_proxy_proxies }}"
  notify:
    - restart nginx

- name: nginx service state
  service: name=nginx state=restarted enabled=yes
