---
# tasks file for ansible-nginx-reverse-proxy
- name: Creates directory
  file:
    path: /var/cache/nginx
    state: directory
    owner: nginx
    group: nginx
    mode: 0775

- name: Install the nginx package
  yum: name=nginx state=latest

- include: deploy.yml
  tags: deploy
- name: nginx service state
  service: name=nginx state=restarted enabled=yes
